# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.105.0
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
ProductCode: '{206E38EC-2C41-48A7-91DA-77F7478A4E0F}'
ReleaseDate: 2025-06-14
AppsAndFeaturesEntries:
- DisplayName: Nushell
  ProductCode: '{206E38EC-2C41-48A7-91DA-77F7478A4E0F}'
  UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
InstallationMetadata:
  DefaultInstallLocation: nu
Installers:
- Architecture: x64
  InstallerUrl: https://terminus-new-trantor.oss-cn-hangzhou.aliyuncs.com/open-tools/misc/nu-0.105.0-x86_64-pc-windows-msvc.msi
  InstallerSha256: EC7A52FD241524036D0CC92239B59224AD9338ACD70C93B2573FC792AD0399AF
ManifestType: installer
ManifestVersion: 1.10.0
