# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.105.0
PackageLocale: en-US
Publisher: The Nushell Project Developers
PublisherUrl: https://www.nushell.sh/
PublisherSupportUrl: https://github.com/nushell/nushell/issues
Author: The Nushell Project Developers
PackageName: nu
PackageUrl: https://github.com/nushell/nushell
License: MIT
LicenseUrl: https://github.com/nushell/nushell/blob/HEAD/LICENSE
Copyright: Copyright (c) 2019 - 2025 The Nushell Project Developers
CopyrightUrl: https://raw.githubusercontent.com/nushell/nushell/main/LICENSE
ShortDescription: A new type of shell
Description: |-
  Hello, and welcome to the Nushell project.
  The goal of this project is to take the Unix philosophy of shells, where pipes connect simple commands together, and bring it to the modern style of development.
  Nu takes cues from a lot of familiar territory, traditional shells like bash, object based shells like PowerShell, functional programming, systems programming, and more.
Moniker: nushell
Tags:
- rust
- shell
ManifestType: defaultLocale
ManifestVersion: 1.10.0
