# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.105.2
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
ProductCode: '{5AD7F008-A56E-4DA0-B059-36537A6AEA53}'
ReleaseDate: 2025-06-14
AppsAndFeaturesEntries:
- DisplayName: Nushell
  ProductCode: '{5AD7F008-A56E-4DA0-B059-36537A6AEA53}'
  UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
InstallationMetadata:
  DefaultInstallLocation: nu
Installers:
- Architecture: x64
  InstallerUrl: https://terminus-new-trantor.oss-cn-hangzhou.aliyuncs.com/open-tools/misc/nu-0.105.2-x86_64-pc-windows-msvc.msi
  InstallerSha256: 6FB53BA4405D72942235F37B2DE9FF321FCC40EB671E94DD578681F35A95B639
ManifestType: installer
ManifestVersion: 1.10.0
