# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.105.2
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
ProductCode: '{06E74398-0409-458F-A478-1B15C8BA8B3B}'
ReleaseDate: 2025-06-14
AppsAndFeaturesEntries:
- DisplayName: Nushell
  ProductCode: '{06E74398-0409-458F-A478-1B15C8BA8B3B}'
  UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
InstallationMetadata:
  DefaultInstallLocation: nu
Installers:
- Architecture: x64
  InstallerUrl: https://terminus-new-trantor.oss-cn-hangzhou.aliyuncs.com/open-tools/misc/nu-0.105.2-x86_64-pc-windows-msvc.msi
  InstallerSha256: 2A4227BC8D860A7EAF0A5590DAE899E81E2313D13B77E7733578C2ED6DD5E208
ManifestType: installer
ManifestVersion: 1.10.0
